trigger:
- none

variables:
  BuildConfiguration: 'Release'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: |
      src/**/*.csproj
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    versioningScheme: versioningScheme
    packagesToPack: 'src/**/*.csproj'
- task: NuGetCommand@2
  displayName: Push
  inputs:
    command: push
    publishVstsFeed: '8f7cbf78-ee6b-4179-89eb-8cb300c05510/355fdd34-a6c7-4a5f-bd91-3d57fa40c1ed'