trigger:
- none

pr: none

variables:
  BuildConfiguration: 'Release'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: |
      src/**/*.csproj
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    versioningScheme: byPrereleaseNumber
    requestedMajorVersion: 0
    requestedMinorVersion: 3
    requestedPatchVersion: 1
    packagesToPack: 'src/**/*.csproj'
- task: NuGetCommand@2
  displayName: Push
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'NuGet (Bungalow64)'
